from PySide6.QtWidgets import QMenuBar

class MenuBar(QMenuBar):
    def __init__(self, parent=None):
        super().__init__(parent)
        self._build_menu()
    def _build_menu(self):
        file_menu = self.addMenu("Файл")
        file_menu.addAction("Создать новый")
        file_menu.addAction("Открыть файл")
        file_menu.addAction("Открыть папку")
        file_menu.addSeparator()
        file_menu.addAction("Сохранить")
        file_menu.addAction("Сохранить как")
        file_menu.addSeparator()
        file_menu.addAction("Выход")
        edit_menu = self.addMenu("Правка")
        edit_menu.addAction("Отмена")
        edit_menu.addAction("Повтор")
        edit_menu.addSeparator()
        edit_menu.addAction("Вырезать")
        edit_menu.addAction("Копировать")
        edit_menu.addAction("Вставить")
        edit_menu.addAction("Удалить")
        edit_menu.addSeparator()
        edit_menu.addAction("Выделить всё")
        view_menu = self.addMenu("Вид")
        view_menu.addAction("Файловый проводник")
        view_menu.addAction("ИИ чат")
        view_menu.addAction("Браузер")
        view_menu.addAction("Текстовый редактор")
        view_menu.addAction("Терминал")
        view_menu.addAction("Генерация изображений")
        view_menu.addAction("ИИ редактор изображений")
        view_menu.addAction("ИИ редактор кода")
        view_menu.addSeparator()
        view_menu.addAction("Сбросить вид")
        view_menu.addSeparator()
        view_menu.addAction("Тема")
        view_menu.addAction("Язык")
        settings_menu = self.addMenu("Настройки")
        help_menu = self.addMenu("Справка")
        help_menu.addAction("Документация")
        help_menu.addAction("О программе")
