"""
Pytest markers for known issues in GopiAI codebase.
Auto-generated by problem discovery system.
"""

import pytest

# Known issue markers for expected failures


def mark_known_issues_GopiAI-CrewAI_tools_gopiai_integration_tools_config():
    """Mark known issues for GopiAI-CrewAI_tools_gopiai_integration_tools_config."""
    markers = []
    markers.append(pytest.mark.xfail(
        reason="Syntax error: unindent does not match any outer indentation level",
        strict=False
    ))
    return markers


def mark_known_issues_GopiAI-CrewAI_tools_crewai_toolkit_tools_llamaindex_tool_llamaindex_tool():
    """Mark known issues for GopiAI-CrewAI_tools_crewai_toolkit_tools_llamaindex_tool_llamaindex_tool."""
    markers = []
    markers.append(pytest.mark.xfail(
        reason="TODO/FIXME comment: we are replacing the schema with our custom schema",
        strict=False
    ))
    return markers
